/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package Backend

@SpringBootApplication
class Application

fun main(args: Array<String>) {
    SpringApplication.run(Application::class.java, *args)
}
